server.servlet.context-path=/db
server.port=8080
server.servlet.session.timeout=90m

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# MySQL connection settings (update these for your environment)
db.host=localhost
db.password=
db.port=3306

# File upload settings
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

upload.directory=/home/pi/Uploads
